site_name: IT-Ops.AI
site_url: https://bwkiwi.github.io/documentation/
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png 
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom-primary
      accent: custom-accent
    - media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      scheme: slate
      primary: custom-primary
      accent: custom-accent

extra_css:
  - stylesheets/custom.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bwkiwi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/brian-hubbard-nzl/

extra:
  version:
    provider: mike
    versions:
      - version: "0.1"
        title: "0.1 (Development)"

nav:
  - Company Page: https://brianhubbardeducat.wixstudio.com/monovandi-test
  - Introduction: index.md
  - GraphQL: 
      - Introduction: graphql/start_here.md
      - Learn More: graphql/learn_more.md

  
markdown_extensions:
  - admonition
  - footnotes
  - attr_list  
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true    
      
plugins:
  - mkdocs-video
  - mike
        
copyright: |
  &copy; 2025 <a href="https://github.com/bwkiwi" target="_blank" rel="noopener">Brian Hubbard</a>